doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    # Assurez-vous que le stockage est configuré par défaut
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'